### PR TITLE
Add collaborator feature

### PR DESCRIPTION
**Pull request by EUGINELETHAL**

### CODE REVIEW

**Comment by EUGINELETHAL** [comment]
@zrthxn @jennydaman 
Screenshot from 2021-11-11 03-57-51
Screenshot from 2021-11-11 03-57-44
This PR create a collaboration management dashboard

**Review by zrthxn — APPROVED** [review]
Great work!

**Comment by zrthxn** [comment]
@EUGINELETHAL Just a small thing, instead of having the "Manage collaborators" button in the card, would it better to have it in the hamburger menu dropdown? Would you make that change?

**Comment by EUGINELETHAL** [comment]
I would definitely .do you  mean placing it in the same section as the edit and
delete links

**Comment by EUGINELETHAL** [comment]
@zrthxn placed the manage collaborators in the hambuger menu
Screenshot from 2021-11-13 13-10-50

**Comment by zrthxn** [comment]
@EUGINELETHAL Great!

**Pull request merged**
