### PR TITLE
“copy url button” added in details page.

### PR DESCRIPTION
**Pull request by anujsingla**
https://github.com/FNNDSC/ChRIS_store_ui/issues/72
@jbernal0019 Please review.

I have updated a couple of packages 
copyurl2
copyurl1

### CODE REVIEW

**Comment by jbernal0019** [comment]
Hey @anujsingla I think there has been a confusion about the place for the “copy url button”.  Actually it should go in the versions tab as **each plugin version has its own url**.  

The overview tab UI should include in some way: `'creation_date', 'modification_date', 'name', 'title', 'stars', 'public_repo', 'license', 'type', 'icon', 'category', 'authors' (contributors), 'documentation'`

In addition I think each plugin version should have its own card in the versions tab. Each card includes `'creation_date', 'version', 'dock_image', 'description', 'min_number_of_workers', 'max_number_of_workers', 'min_cpu_limit', 'max_cpu_limit', 'min_memory_limit', 'max_memory_limit', 'min_gpu_limit', 'max_gpu_limit'`     @mairin Is this something that was included in the mocks?

**Comment by anujsingla** [comment]
Hey @jbernal0019 As per the new design https://github.com/FNNDSC/ChRIS_store_ui/issues/81
We need to show `copy url button` in the overview tab and I have already added in the Overview tab so I think we can merge this MR.
Please let me know if you need more details.

**Comment by jbernal0019** [comment]
Hey @anujsingla  The `copy url button` should show the url of the individual plugin version shown on the new dropdown. Is that the case then yes, we can merge. 

Please fix the conflicting files `src/components/Plugin/Plugin.css` so I can merge.

**Comment by anujsingla** [comment]
@jbernal0019 Resolved conflicting files, Please merged it.

**Pull request merged**
