### PR TITLE
Apps names and icons replaced

### PR DESCRIPTION
**Pull request by DivyanshiSingh**
Fixes: #169 
1) Changed the names and icons of apps as mentioned in the issue.

### CODE REVIEW

**Review by jennydaman — CHANGES_REQUESTED** [review]
Actually it looks good!

Could you make the icons link to their respective plugins?

**Comment by DivyanshiSingh** [comment]
of course. I will do it soon

**Comment by jennydaman** [comment]
Also to differentiate infant freesurfer from freesurfer, perhaps we should use a color filter, or maybe add a second small icon in the corner.

Maybe https://github.com/FNNDSC/chrisreloaded/blob/master/plugins/fetal_moco/feed.png
Or find an open-source icon of "child" "infant" "baby"

**Comment by DivyanshiSingh** [comment]
hey @jennydaman as mentioned by you to link an icon with their respective plugins, so where do we have to link the icon?
Does this change need to be done on the links given to me on the issue like https://next.chrisstore.co/plugin/44? If yes, then where is it as I couldn't find any such option of icon upload on the plugin link?

**Comment by jennydaman** [comment]
e.g. the icon for CIVET should link to https://next.chrisstore.co/plugin/2
Does that answer your question?

**Comment by DivyanshiSingh** [comment]
Yeah sure...thank you @jennydaman

**Comment by jennydaman** [comment]
Hey @DivyanshiSingh an impactful PR has been merged, #162 
Please merge `pf4` into your working tree

**Comment by DivyanshiSingh** [comment]
Hey, @jennydaman I have done the required changes, please review.

**Comment by jennydaman** [comment]
What do you mean by misplaced?

**Review by jennydaman — COMMENTED** [review]
Is it possible to have these be regular links (which do not open in a new tab)?

**Comment by DivyanshiSingh** [comment]
> Is it possible to have these be regular links (which do not open in a new tab)?

I have made the links regular, please review.

**Review by jennydaman — APPROVED** [review]

**Comment by jennydaman** [comment]
And that marks "1.0"!

**Pull request merged**
