### PR TITLE
Issue18 Pull request

### PR DESCRIPTION
**Pull request by gagansk**
A pull request from a non-master branch to accommodated a suggestion made by @jcaianirh

### CODE REVIEW

**Comment by gagansk** [comment]
@jcaianirh , a pull request has been made for https://github.com/FNNDSC/ChRIS_store_ui/issues/18 from a non-master forked branch.

**Comment by jcaianirh** [comment]
@mairin @jdtzmn @gagansk we should standardize on a validation pattern. See the login form and create plugin form.

**Comment by jcaianirh** [comment]
@jdtzmn Will this pr satisfy the issue or will we need a follow on pr to handle errors returned from the back end?

**Comment by gagansk** [comment]
Pull request is approved and merged.

**Pull request merged**
