### PR TITLE
Add travis and fix test bug

### LINKED ISSUE #37: Travis Integration?
It might be helpful to have a Travis CI integration in order to run the unit tests.
I'm thinking that it would be nice to be able to see the status of the tests for each pull request.
Would you be interested in me adding this @jcaianirh?

### PR DESCRIPTION
**Pull request by jdtzmn**
Added .travis.yml and fixed the bug that was breaking tests.

**There are 57 broken tests that need fixing**

Closes #37

### CODE REVIEW

**Comment by jcaianirh** [comment]
@jdtzmn Looks good. Thanks for integrating travis. To move forward do you want me to use this branch to fix broken tests or will this pr be mergeable with failing travis tests?

**Comment by jdtzmn** [comment]
@jcaianirh Feel free to use this branch to fix the errors. In the future it might be a good idea to require pull requests to pass tests before merging, but that's up to you and @jbernal0019.

**Comment by jbernal0019** [comment]
@jdtzmn It was approved by the reviewer, right? I also thought that you guys had agreed to work on that branch. Anyway you're right,  PR shouldn't be made and merged if the tests fail. Please see if you can fix it. Thanks!

**Comment by jdtzmn** [comment]
@jbernal0019 No worries. I wasn't sure if it was an accident or something you and @jcaianirh had talked about. It will, however, require a new pull request in order to fix the broken tests on the master branch right now.

**Pull request merged**
