### PR TITLE
prerender routes with react-snap

### PR DESCRIPTION
**Pull request by Aaishpra**
Fixes: #99 

Pre-render routes with react-snap to speed up the performance of the site.

### CODE REVIEW

**Comment by jennydaman** [comment]
I am unable to build.

```bash
git clone --branch=prerender-routes git@github.com:Aaishpra/ChRIS_store_ui.git
cd ChRIS_store_ui
docker build .
```

Result is

```
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Compiled successfully.

File sizes after gzip:

  206.9 KB         build/static/js/2.7e57158b.chunk.js
  99.06 KB (+1 B)  build/static/js/main.fe800a56.chunk.js
  71.79 KB         build/static/css/2.a47ac322.chunk.css
  5.32 KB          build/static/css/main.7cc01631.chunk.css
  774 B            build/static/js/runtime-main.1a203ea9.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

$ react-snap
Error: Failed to launch chrome! spawn /app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:348:14)
    at ChildProcess.<anonymous> (/app/node_modules/puppeteer/lib/Launcher.js:339:64)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn install && yarn build' returned a non-zero code: 1
```

**Comment by Aaishpra** [comment]
I will look into it @jennydaman, although I completely followed the  tutorial you provided in the issue comments section

**Comment by jennydaman** [comment]
The tutorial I provided was meant to be an intro to the topic. If only things in software worked as-is....

**Comment by Aaishpra** [comment]
Hey, @jennydaman can you check if it's working for you now. I made some changes to the files, although still getting this error (maybe because I don't have chrome on my system)

Response after running `yarn run build `
```
$ react-snap
{ TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r686378
    at Timeout.onTimeout (/home/user/ChRIS_store_ui/node_modules/puppeteer/lib/Launcher.js:359:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
error Command failed with exit code 1.
```

**Comment by jennydaman** [comment]
Hey @Aaishpra, this issue seems more complicated than I originally thought (pre-rendering is just a flag to tick for a different JS framework, preact)

It gives me a different error. What is your OS? I do not have chrome installed either, but I do have chromium.

If I were to guess, it's crawling the build artifact using headless chrome to render the pages. I think the crawler is failing on invalid links in the plugin details pages. I do not have time atm to investigate further. I will give this issue more attention tomorrow.

```
yarn run build
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Compiled with warnings.

./src/index.js
  Line 2:8:  'ReactDOM' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  206.89 KB  build/static/js/2.802d367c.chunk.js
  99.06 KB   build/static/js/main.b2c7ab32.chunk.js
  72.16 KB   build/static/css/2.9375f4d1.chunk.css
  5.41 KB    build/static/css/main.94ed59d7.chunk.css
  774 B      build/static/js/runtime-main.1a203ea9.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

$ react-snap
💬  console.log at /: Content is cached for offline use.
💬  console.log at /: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
✅  crawled 1 out of 5 (/)
💬  console.log at /signin: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /404.html: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /plugins: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /quickstart: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
✅  crawled 2 out of 5 (/signin)
✅  crawled 3 out of 5 (/quickstart)
⚠️  warning: 404 page title does not contain "404" string
✅  crawled 4 out of 5 (/404.html)
✅  crawled 5 out of 7 (/plugins)
💬  console.log at /author/FNNDSC%20%3Cdev@babyMRI.org%3E: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /plugin/1: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
✅  crawled 6 out of 10 (/author/FNNDSC%20%3Cdev@babyMRI.org%3E)
✅  crawled 7 out of 10 (/plugin/1)
💬  console.log at /plugin/https://wiki.wiki: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
⚠️  warning at /plugin/https://wiki.wiki: got 400 HTTP code for http://localhost:8010/api/v1/plugins/search/?id=NaN
💬  console.log at /plugin/https://wiki.wiki: Failed to load resource: the server responded with a status
 of 400 (Bad Request)
💬  console.log at /plugin/Simple%20chris%20ds%20app: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
⚠️  warning at /plugin/Simple%20chris%20ds%20app: got 400 HTTP code for http://localhost:8010/api/v1/plugins/search/?id=NaN
💬  console.log at /plugin/Simple%20chris%20ds%20app: Failed to load resource: the server responded with a status of 400 (Bad Request)
💬  console.log at /plugin/FNNDSC%20%3Cdev@babyMRI.org%3E: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
⚠️  warning at /plugin/FNNDSC%20%3Cdev@babyMRI.org%3E: got 400 HTTP code for http://localhost:8010/api/v1/plugins/search/?id=NaN
💬  console.log at /plugin/FNNDSC%20%3Cdev@babyMRI.org%3E: Failed to load resource: the server responded with a status of 400 (Bad Request)
🔥  pageerror at /plugin/https://wiki.wiki: o: {"id": ["Enter a number."]}
    at Function.value (../node_modules/@fnndsc/chrisstoreapi/dist/chrisstoreapi.js:8:21622)
🔥  pageerror at /plugin/Simple%20chris%20ds%20app: o: {"id": ["Enter a number."]}
    at Function.value (../node_modules/@fnndsc/chrisstoreapi/dist/chrisstoreapi.js:8:21622)
🔥  pageerror at /plugin/FNNDSC%20%3Cdev@babyMRI.org%3E: o: {"id": ["Enter a number."]}
    at Function.value (../node_modules/@fnndsc/chrisstoreapi/dist/chrisstoreapi.js:8:21622)
✅  crawled 8 out of 10 (/plugin/https://wiki.wiki)
✅  crawled 9 out of 10 (/plugin/Simple%20chris%20ds%20app)
✅  crawled 10 out of 10 (/plugin/FNNDSC%20%3Cdev@babyMRI.org%3E)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run build  88.57s user 4.28s system 129% cpu 1:11.54 total
```

**Comment by Aaishpra** [comment]
@jennydaman it was the same error for me when I first ran this command (basically not an error, something similar happened but in the end, it showed `Done in x.__ secs`, instead of `error Command failed with exit code 1`, ran the command again and got the above-mentioned error (`Failed to launch chrome`). I am going to install chrome on my system and check again to see if it works or not.
And, I am using Ubuntu 20.04 LTS on my laptop.

**Comment by Aaishpra** [comment]
```
$ react-snap
✅  crawled 1 out of 5 (/)
💬  console.log at /plugins: Failed to load resource: net::ERR_CONNECTION_REFUSED
💬  console.log at /plugins: o: No server response!
💬  console.log at /signin: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /404.html: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /plugins: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
💬  console.log at /quickstart: This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ
✅  crawled 2 out of 5 (/signin)
⚠️  warning: 404 page title does not contain "404" string
✅  crawled 3 out of 5 (/404.html)
✅  crawled 4 out of 5 (/plugins)
✅  crawled 5 out of 5 (/quickstart)
Done in 175.03s.
```

**Comment by jennydaman** [comment]
That is interesting! Did it work?

You can verify pre-rendering by doing either:

- disable JavaScript in your browser and try seeing the page
- open the built `index.html` and see if there's actual content in there

We'd want to have a fully open-source build chain, so if it's possible to configure `react-snap` to use `chromium`, that'd be better. (Best would be to find a free, open-source solution without chromium either, as it'd add weight to a continuous integration environment... but such a tool might not exist for React.js)

**Comment by Aaishpra** [comment]
No, It didn't 😭 just getting this every time I run the command even after installing chrome, It's not launching the browser. I guess I would have to look into this more.

> We'd want to have a fully open-source build chain, so if it's possible to configure react-snap to use chromium, that'd be better. (Best would be to find a free, open-source solution without chromium either, as it'd add weight to a continuous integration environment... but such a tool might not exist for React.js)

Will definitely try this first trying to make this work in chrome

**Comment by jennydaman** [comment]
@Aaishpra I am rethinking this. (It could be one reason why there is less support for pre-rendering with React.js,) It seems like there are more tools for **server-side rendering** aka SSR of React.js (rather than pre-rendering). Originally I dismissed SSR in hopes of keeping the website static where it can be static, but that intuition was misguided. SSR would be a valuable enhancement for the pages with dynamic content, such as: 

https://chrisstore.co/plugins
https://chrisstore.co/plugin/77

I am not sure whether SSR will be simple to do, or if it will require an in-depth restructuring of the code base. Neither do I have experience with how it might play out with the create-react-app's paradigms. Nonetheless it is an option to explore.

**Comment by Aaishpra** [comment]
Well, I also have never tried server side rendering but yupp definitely it can be a good option to explore since Pre rendering is not working here.
Currently reading about it, will share my thoughts about it.

**Comment by jennydaman** [comment]
Stale

**Pull request closed without merging**
